name: health_and_doctor_appointment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  flutter_tabler_icons: ^1.0.2
  cloud_firestore: ^5.6.0
  provider: ^6.0.3
  cool_alert: ^2.0.1
  google_nav_bar: ^5.0.5
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^5.0.0
  quick_actions: ^1.1.0
  introduction_screen: ^3.1.14
  flutter_vector_icons: ^2.0.0
  material_symbols_icons: ^4.2801.1
  typicons_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
